env:
  browser: true
  commonjs: true
  es6: true
  node: true
  mocha: true
extends:
  - 'plugin:react/recommended'
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
plugins:
  - react
rules:
  no-unused-expressions: 'off'
settings:
  react:
    version: detect
