env:
  browser: true
  commonjs: true
  es6: true
  node: true
  mocha: true
extends:
  - 'plugin:react/recommended'
  - standard
  - plugin:import/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  babelOptions:
    presets: 
      - '@babel/preset-react'
plugins:
  - react
  - import
rules:
  no-unused-expressions: 'off'
  react/react-in-jsx-scope: 'off'
  react/no-unknown-property:
    - 2
    - ignore:
      - 'jsx'
  import/no-commonjs: 2
settings:
  react:
    version: detect
