parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - 'prettier'
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/recommended'
  - 'plugin:jsdoc/recommended'
rules:
  prettier/prettier: 'error'
  semi: 
    - 2
    - always
  space-before-function-paren:
    - 2
    - anonymous: never
      named: never
      asyncArrow: always
  comma-dangle:
    - 2
    - always-multiline
settings:
  'import/resolver':
    typescript:
      alwaysTryTypes: true