name: Bun CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version:
          - latest
          - canary
          - "0.5.6"

    steps:
    - uses: actions/checkout@v2
    - name: Use Bun ${{ matrix['bun-version'] }}
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ matrix['bun-version'] }}
    - run: bun install
    - run: bun run lint
    - run: bun run test
