name: Basic CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix['node-version'] }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix['node-version'] }}
    - run: npm ci
    - run: npm run lint
    - run: npm test
    - run: docker-compose up -d db mq
    - run: sleep 15
    - run: npm run migrate
    - run: npx pm2 start deployments/default/ecosystem.yaml
    - run: sleep 30
    - run: npx pm2 logs --nostream
    - run: npm run integration
    - run: npx pm2 kill
